eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8000
spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    
  sleuth:
    sampler:
      probability: 1.0
    
resilience4j:
  retry:
    instances:
      currency-exchange:
        max-attempts: 5
        wait-duration: 1s
  circuitbreaker:
    instances:
      currency-exchange:
        failure-rate-threshold: 90
  ratelimiter:
    instances:
      currency-exchange:
        limit-for-period: 1000
        limit-refresh-period: 10s
  bulkhead:
    instances:
      currency-exchange:
        max-concurrent-calls: 100
        max-wait-duration: 1s
  
        


